public enum TypeAnamneseEnfant {
    STRUCTURE FAMILIALE,
    DYNAMIQUE FAMILIALE,
    ANTECEDENTS FAMILIAUX,
    CONDITIONS NATALES,
    DEVELOPPEMENT PSYCHOMOTEUR,
    DEVELOPPEMENT LANGAGIER,
    CARACTERE ET COMPOTEMENT,
    }