package com.example.tp.Models;

public enum TypeAnamneseEnfant {
    STRUCTUREFAMILIALE,
    DYNAMIQUEFAMILIALE,
    ANTECEDENTSFAMILIAUX,
    CONDITIONSNATALES,
    DEVELOPPEMENTPSYCHOMOTEUR,
    DEVELOPPEMENTLANGAGIER,
    CARACTEREETCOMPOTEMENT
    }